[package]
name = "aah"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["packages/*"]

[workspace.dependencies]
aah-core = { path = "packages/aah-core" }
aah-cv = { path = "packages/aah-cv" }
aah-resource = { path = "packages/aah-resource" }
image = "0.25.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aah-core.workspace = true
clap = { version = "4.4.12", features = ["derive"] }
env_logger = "0.10.1"
