[Multi]
fail_fast = false
tasks = [
    { Navigate = { NavigateIn = "mission" } },
    "press_collect_all_award",
    "confirm",
    { ActionClickMatch = { match_task = { type = "Template", template = "award_2.png" } } },
    "press_collect_all_award",
    # "confirm", 匹配率不是很好
    { ActionClick = { x = 100, y = 100 } },
    { Navigate = { NavigateOut = "mission" } },
]
