name = "award"

[[steps]]

[steps.action]
ByName = "enter_mission"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ClickMatchTemplate]
template = "mission-week_collect-all.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ClickMatchTemplate]
template = "confirm.png"

[[steps]]
delay_sec = 0.5
retry = 1

[steps.action.ClickMatchTemplate]
template = "mission-day_week.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ClickMatchTemplate]
template = "mission-week_collect-all.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ClickMatchTemplate]
template = "confirm.png"

[[steps]]

[steps.action]
ByName = "back"