name = "award"

[[steps]]

[steps.action]
NavigateIn = "mission"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ActionClickMatchTemplate]
template = "mission-week_collect-all.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ActionClickMatchTemplate]
template = "confirm.png"

[[steps]]
delay_sec = 0.5
retry = 1

[steps.action.ActionClickMatchTemplate]
template = "mission-day_week.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ActionClickMatchTemplate]
template = "mission-week_collect-all.png"

[[steps]]
delay_sec = 0.5
skip_if_failed = true
retry = 1

[steps.action.ActionClickMatchTemplate]
template = "confirm.png"

[[steps]]

[steps.action]
NavigateOut = "mission"