[base.enter_task.ActionClickMatch.match_task]
type = "Template"
template = "EnterInfrastMistCity.png"

[base.exit_task.ByName]
name = "back"

[mission.enter_task.ActionClickMatch.match_task]
type = "Template"
template = "EnterMissionMistCity.png"

[mission.exit_task.ByName]
name = "back"
