[base.enter_task.ActionClickMatch.match_task]
type = "Template"
template = "main_base.png"

[base.exit_task.ByName]
name = "back"

[mission.enter_task.ActionClickMatch.match_task]
type = "Template"
template = "main_mission.png"

[mission.exit_task.ByName]
name = "back"
