[swipe_right.ActionSwipe]
p1 = [
    0,
    0,
]
p2 = [
    200,
    0,
]
duration = 1.0

[multiple.Multi]
fail_fast = false

[[multiple.Multi.tasks]]

[multiple.Multi.tasks.ActionPressEsc]

[[multiple.Multi.tasks]]
NavigateIn = "name"

[[multiple.Multi.tasks]]

[multiple.Multi.tasks.ActionPressHome]

[[multiple.Multi.tasks]]

[multiple.Multi.tasks.ActionClick]
x = 0
y = 0

[multiple.Multi.tasks.ActionClick.wrapper]
delay = 0.0
retry = 0
repeat = 1

[[multiple.Multi.tasks]]

[multiple.Multi.tasks.ActionSwipe]
p1 = [
    0,
    0,
]
p2 = [
    200,
    0,
]
duration = 1.0

[[multiple.Multi.tasks]]

[multiple.Multi.tasks.ByName]
name = "press_esc"

[multiple.Multi.tasks.ByName.wrapper]
delay = 0.0
retry = 0
repeat = 1

[press_esc.ActionPressEsc]

[click_origin.ActionClick]
x = 0
y = 0

[click_origin.ActionClick.wrapper]
delay = 0.0
retry = 0
repeat = 1

[navigate_out]
NavigateIn = "name"

[press_home.ActionPressHome]

[toggle_top_navigator.ActionClickMatch.match_task]
type = "Template"
template = "ButtonToggleTopNavigator.png"

[navigate_in]
NavigateIn = "name"

[by_name.ByName]
name = "press_esc"

[by_name.ByName.wrapper]
delay = 0.0
retry = 0
repeat = 1
