[package]
name = "aah-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel.workspace = true
image.workspace = true
anyhow.workspace = true
color-print = "0.3.7"
env_logger = "0.11.6"
log = "0.4.25"
rand = "0.9.0"
tempfile = "3.16.0"
