[package]
name = "aah-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.7"
crossbeam-channel = "0.5.14"
env_logger = "0.11.6"
image.workspace = true
log = "0.4.25"
rand = "0.9.0"
