[package]
name = "aah-resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
image.workspace = true
serde = { version = "1.0.217", features = ["derive"] }
serde_with = { version = "3.12.0", features = ["macros"] }
serde_json = "1.0.128"
serde_repr = "0.1.19"
nalgebra = "0.33.0"
git2 = "0.20.0"
reqwest = { version = "0.12.7", features = ["json"] }
time = { version = "0.3.36", features = ["serde", "parsing", "macros"] }
tracing = "0.1.40"
toml = "0.8.19"
zip = "2.2.0"
vfs = "0.12.0"
bytes = "1.7.2"

[dev-dependencies]
tokio = { version = "1.39.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
