[package]
name = "aah-resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_repr = "0.1.19"
nalgebra = "0.33.0"
image = "0.25.1"
anyhow = "1.0.89"
git2 = "0.19.0"
reqwest = { version = "0.12.7", features = ["json"] }
time = { version = "0.3.36", features = ["serde", "parsing", "macros"] }
tracing = "0.1.40"
toml = "0.8.19"

[dev-dependencies]
tokio = { version = "1.39.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
