[package]
name = "aah-cv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
bytemuck = { version = "1.14.1", features = ["derive"] }
futures-intrusive = "0.5.0"
imageproc = "0.23.0"
ndarray = "0.15.6"
ndarray-csv = "0.5.2"
nshare = "0.9.0"
pollster = "0.3.0"
rustfft = "6.2.0"
wgpu = "0.19"
fft2d = "0.1.1"
fftconvolve = "0.1.1"
csv = "1.3.0"
easyfft = "0.4.1"
nalgebra = "0.32.5"
flume = "0.11.0"
num = "0.4.2"
serde = "1.0.210"
