[package]
name = "aah-cv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.14.1", features = ["derive"] }
futures-intrusive = "0.5.0"
image = "0.24.8"
imageproc = "0.23.0"
pollster = "0.3.0"
wgpu = "0.19.1"
