[package]
name = "maa-resource"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = { version = "0.4.38", features = ["serde"] }
git2 = "0.19.0"
reqwest = { version = "0.12.7", features = ["json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
time = { version = "0.3.36", features = ["serde", "parsing", "macros"] }
tracing = "0.1.40"

[dev-dependencies]
tokio = { version = "1.39.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }