name = "1-4"
level_code = "1-4"

[operators]
durin = "char_501_durin"
spot = "char_284_spot"
lancet = "char_285_medic2"
yato = "char_502_nblade"
noir_corne = "char_500_noirc"
rangers = "char_503_rang"
ansel = "char_212_ansel"
myrtle = "char_151_myrtle"
melantha = "char_208_melan"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "myrtle"
position = [
    2,
    1,
]
direction = "Right"

[[steps]]
time = "Asap"

[steps.action.AutoSkill]
operator = "myrtle"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "yato"
position = [
    3,
    1,
]
direction = "Right"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "noir_corne"
position = [
    4,
    1,
]
direction = "Right"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "melantha"
position = [
    2,
    2,
]
direction = "Down"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "ansel"
position = [
    5,
    2,
]
direction = "Up"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "rangers"
position = [
    1,
    3,
]
direction = "Down"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "durin"
position = [
    5,
    3,
]
direction = "Up"

[[steps]]
time = "Asap"

[steps.action.Retreat]
operator = "yato"

[[steps]]
time = "Asap"

[steps.action.Deploy]
operator = "spot"
position = [
    3,
    1,
]
direction = "Up"