[package]
name = "aah-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aah-controller.workspace = true
aah-cv.workspace = true
aah-resource.workspace = true
image.workspace = true
crossbeam-channel = "0.5.13"
imageproc = "0.25.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
serde_json = "1.0.110"
ocrs = "0.8.1"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
log = "0.4"
color-print = "0.3.5"
serde_with = { version = "3.8.3", features = ["macros"] }
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
async-channel = "2.3.1"
futures = { version = "0.3.30", optional = true }
rten = "0.13.1"
regex = "1.10.5"
zip = "2.2.0"
bytes = "1.7.2"
time = { version = "0.3.36", features = ["serde", "parsing", "macros"] }

[dev-dependencies]
env_logger = "0.10.0"
regex = "1.10.5"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
