[package]
name = "aah-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
imageproc = "0.23.0"
template-matching = { version = "0.2.0", features = ["image"] }
rand = "0.8"
# leptess = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
serde_json = "1.0.110"
ocrs = "0.3.1"
rten = "0.2.0"
rten-tensor = "0.1.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
